-- Supabase setup for this app.
-- Run this once in Supabase Dashboard -> SQL Editor.
--
-- Note: this project currently uses custom mobile/password login from the
-- browser. This schema creates the tables the app expects, but it does not add
-- broad public RLS policies. For production, move login/register/database
-- writes behind server routes and use hashed passwords.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  full_name text,
  mobile text not null unique,
  email text,
  password text not null,
  balance numeric(12, 2) not null default 0,
  operator text,
  kyc_verified boolean not null default false,
  kyc_status text not null default 'not_submitted'
    check (kyc_status in ('not_submitted', 'pending', 'verified', 'rejected')),
  status text not null default 'active'
    check (status in ('active', 'inactive', 'blocked')),
  total_earnings numeric(12, 2) not null default 0,
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_mobile_idx on public.users (mobile);
create index if not exists users_status_idx on public.users (status);
create index if not exists users_kyc_status_idx on public.users (kyc_status);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  user_mobile text,
  type text not null default 'data_sell',
  amount numeric(12, 2) not null default 0,
  description text,
  status text not null default 'completed'
    check (status in ('pending', 'completed', 'failed', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_id_idx on public.transactions (user_id);
create index if not exists transactions_user_mobile_idx on public.transactions (user_mobile);
create index if not exists transactions_created_at_idx on public.transactions (created_at desc);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  user_mobile text,
  amount numeric(12, 2) not null,
  payment_method text not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'completed', 'rejected', 'failed')),
  transaction_id text unique,
  upi_id text,
  bank_name text,
  account_number text,
  ifsc_code text,
  account_holder text,
  paytm_number text,
  google_pay_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists withdrawals_user_id_idx on public.withdrawals (user_id);
create index if not exists withdrawals_user_mobile_idx on public.withdrawals (user_mobile);
create index if not exists withdrawals_created_at_idx on public.withdrawals (created_at desc);

drop trigger if exists withdrawals_set_updated_at on public.withdrawals;
create trigger withdrawals_set_updated_at
before update on public.withdrawals
for each row execute function public.set_updated_at();

create table if not exists public.kycdetail (
  id bigint generated by default as identity primary key,
  loggedin_number text,
  full_name text not null,
  mobile text not null,
  email text,
  date_of_birth date,
  status text not null default 'pending'
    check (status in ('pending', 'verified', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists kycdetail_mobile_idx on public.kycdetail (mobile);
create index if not exists kycdetail_loggedin_number_idx on public.kycdetail (loggedin_number);
create index if not exists kycdetail_status_idx on public.kycdetail (status);

drop trigger if exists kycdetail_set_updated_at on public.kycdetail;
create trigger kycdetail_set_updated_at
before update on public.kycdetail
for each row execute function public.set_updated_at();

create table if not exists public.kycpayments (
  id bigint generated by default as identity primary key,
  mobile text not null,
  utr text not null unique,
  screenshot text not null,
  status text not null default 'pending'
    check (status in ('pending', 'verified', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists kycpayments_mobile_idx on public.kycpayments (mobile);
create index if not exists kycpayments_status_idx on public.kycpayments (status);

drop trigger if exists kycpayments_set_updated_at on public.kycpayments;
create trigger kycpayments_set_updated_at
before update on public.kycpayments
for each row execute function public.set_updated_at();

create table if not exists public.verify (
  id bigint generated by default as identity primary key,
  mobile text,
  utr text,
  screenshot text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);
